## 配置数据源信息
spring:
  datasource:
    # 数据源类型: HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    # mysql驱动
    driver-class-name: com.mysql.jdbc.Driver
    # jdbc的url地址
    url: jdbc:mysql://47.112.125.251:3369/db2?useUnicode=true&characterEncoding=utf8&useSSL=false
    # 用户名称
    username: db1
    # 密码
    password: db2_1234

    hikari:
      # 等待连接池分配连接的最大时长(毫秒)
      connection-timeout: 3000
      # 最小连接数
      minimum-idle: 20
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长(毫秒), 超时则被释放(retired)
      idle-timeout: 600000
      # 连接池名称l
      pool-name: DataSourceHikariCP
      # 连接的生命时长(毫秒)
      max-lifetime: 1800000
      # 测试连接的语句, 主要是为了防止连接断开
      connection-test-query: SELECT 1

## mybatis 配置
mybatis:
  # 定义实体类所在的包路径
  type-aliases-package: org.example.pojo.entity
  # mapper映射文件所在的路径
  mapper-locations: classpath:mybatis/*.xml
  # 开启 mybatis 日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


## tomcat 配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

## 分页插件配置
pagehelper:
  helper-dialect: MYSQL
  support-methods-arguments: true